#!/bin/bash
#
# Generate Mock Test Data
# Creates realistic test data for load testing
#
# Usage: ./tests/generate-mock-data.sh [count]
#   count: Number of bookings to generate (default: 50)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

COUNT="${1:-50}"
SALON_ID="${2:-550e8400-e29b-41d4-a716-446655440000}"

echo "========================================"
echo "SalonBooker Mock Data Generator"
echo "========================================"
echo "Generating: $COUNT test bookings"
echo "Salon ID: $SALON_ID"
echo ""

# Load environment
if [ -f "$PROJECT_DIR/.env.test" ]; then
    set -a
    source "$PROJECT_DIR/.env.test"
    set +a
fi

if [ -z "$NEXT_PUBLIC_SUPABASE_URL" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
    echo "❌ Required environment variables not set"
    exit 1
fi

echo "🔄 Generating mock bookings..."

# Get existing services and staff for references
echo "   Fetching services and staff..."
services=$(curl -s "${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/services?select=id,name,duration,price&salon_id=eq.${SALON_ID}&is_active=eq.true" \
    -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
    -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" 2>/dev/null)

staff=$(curl -s "${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/staff?select=id,name&salon_id=eq.${SALON_ID}&is_active=eq.true" \
    -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
    -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" 2>/dev/null)

service_count=$(echo "$services" | jq 'length')
staff_count=$(echo "$staff" | jq 'length')

echo "   Found $service_count services, $staff_count staff members"

if [ "$service_count" -eq 0 ] || [ "$staff_count" -eq 0 ]; then
    echo "❌ Cannot generate bookings without services and staff"
    exit 1
fi

# Generate mock data
echo "   Creating bookings..."

first_names=("Anna" "Mark" "Lisa" "Peter" "Sarah" "John" "Emma" "Tom" "Sophie" "David")
last_names=("de Vries" "Janssen" "Bakker" "Jansen" "van Dijk" "Smit" "Mulder" "van den Berg" "Jacobs" "Willems")
statuses=("pending" "confirmed" "completed")

created=0
failed=0

for i in $(seq 1 $COUNT); do
    first_name=${first_names[$((RANDOM % ${#first_names[@]}))]}
    last_name=${last_names[$((RANDOM % ${#last_names[@]}))]}
    customer_name="$first_name $last_name"
    customer_phone="06-$((10000000 + RANDOM % 89999999))"
    customer_email="$(echo "$customer_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '.')@mockdata.nl"
    
    service_idx=$((RANDOM % service_count))
    service=$(echo "$services" | jq -r ".[$service_idx]")
    service_id=$(echo "$service" | jq -r '.id')
    service_name=$(echo "$service" | jq -r '.name')
    service_duration=$(echo "$service" | jq -r '.duration')
    service_price=$(echo "$service" | jq -r '.price')
    
    staff_idx=$((RANDOM % staff_count))
    staff_id=$(echo "$staff" | jq -r ".[$staff_idx].id")
    
    # Random date in next 30 days
    days_ahead=$((RANDOM % 30))
    booking_date=$(date -d "+$days_ahead days" +%Y-%m-%d 2>/dev/null || date -v+"${days_ahead}"d +%Y-%m-%d)
    
    # Random time slot (9:00 - 17:00)
    hour=$((9 + RANDOM % 9))
    minute=$((RANDOM % 4 * 15))
    booking_time=$(printf "%02d:%02d" $hour $minute)
    
    status=${statuses[$((RANDOM % ${#statuses[@]}))]}
    
    booking_payload=$(jq -n \
        --arg salon_id "$SALON_ID" \
        --arg service_id "$service_id" \
        --arg staff_id "$staff_id" \
        --arg service_name "$service_name" \
        --arg service_duration "$service_duration" \
        --argjson service_price "$service_price" \
        --arg customer_name "$customer_name" \
        --arg customer_phone "$customer_phone" \
        --arg customer_email "$customer_email" \
        --arg booking_date "$booking_date" \
        --arg booking_time "$booking_time" \
        --arg status "$status" \
        '{
            salon_id: $salon_id,
            service_id: $service_id,
            staff_id: $staff_id,
            service_name: $service_name,
            service_duration: $service_duration,
            service_price: $service_price,
            customer_name: $customer_name,
            customer_phone: $customer_phone,
            customer_email: $customer_email,
            booking_date: $booking_date,
            booking_time: $booking_time,
            status: $status,
            notes: "Generated by mock data script"
        }')
    
    response=$(curl -s -w "\n%{http_code}" "${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/bookings" \
        -X POST \
        -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
        -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
        -H "Content-Type: application/json" \
        -d "$booking_payload" 2>/dev/null)
    
    http_code=$(echo "$response" | tail -n1)
    
    if [ "$http_code" = "201" ]; then
        ((created++))
        if [ $((i % 10)) -eq 0 ]; then
            echo "   Progress: $i/$COUNT"
        fi
    else
        ((failed++))
    fi
done

echo ""
echo "========================================"
echo "Mock Data Generation Complete"
echo "========================================"
echo "✅ Created: $created bookings"
echo "❌ Failed: $failed bookings"
echo ""

# Show updated counts
echo "📊 Current booking counts by status:"
curl -s "${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/bookings?select=status" \
    -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
    -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" 2>/dev/null | \
    jq -r 'group_by(.status) | map({status: .[0].status, count: length}) | .[] | "   \(.status): \(.count)"'

echo ""
